### ISSUE TITLE
About automatic evaluation

### ISSUE THREAD

**Issue by Mei0211** [llyx97/FETV-EVAL#2]
Thank you for your wonderful work! I would like to ask why the results of clipscore and blipscore only have one score, but there are six attributes scored in the paper (for example: assets/corr_results.png). Where is the script for automated evaluation of the six attributes?

**Comment by llyx97** [comment]
Yes, for each single video, we only calculate one CLIPScore/BLIPScore. To derive the auto-human correlation for a particular attribute, we calculate CLIPScore/BLIPScore for all the videos that involve this attribute. Subsequently, we compute the correlation coefficient between the associated CLIPScores/BLIPScores and human ratings.
